// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SpellService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::SpellServer;

class SpellServiceHandler : virtual public SpellServiceIf {
 public:
  SpellServiceHandler() {
    // Your initialization goes here
  }

  void spellcheck(SpellResponse& _return, const SpellRequest& request) {
    // Your implementation goes here
    printf("spellcheck\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<SpellServiceHandler> handler(new SpellServiceHandler());
  shared_ptr<TProcessor> processor(new SpellServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

