/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SpellServer_CONSTANTS_H
#define SpellServer_CONSTANTS_H

#include "SpellServer_types.h"

namespace SpellServer {

class SpellServerConstants {
 public:
  SpellServerConstants();

};

extern const SpellServerConstants g_SpellServer_constants;

} // namespace

#endif
