/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SpellServer_constants.h"

namespace SpellServer {

const SpellServerConstants g_SpellServer_constants;

SpellServerConstants::SpellServerConstants() {
}

} // namespace

